name: PropHunt
version: 1.0
main: me.Swumo.PropHunt.PropHunt
api-version: 1.21
commands:
  prophunt:
    description: Main PropHunt command
    aliases: [ph]
permissions:
  prophunt.admin:
    description: Admin control of PropHunt games
    default: op
